web/router.ex
defmodule Pairmotron.Router do
  use Pairmotron.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :authenticate do
    plug Pairmotron.Plug.RequireAuthentication
  end

  pipeline :admin do
    plug Pairmotron.Plug.RequireAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  scope "/", Pairmotron do
    pipe_through :browser

    resources "/registration", RegistrationController, only: [:new, :create]
    get "/forgot_password", PasswordResetController, :new
    post "/forgot_password", PasswordResetController, :create
    get "/forgot_password/reset/:token_string", PasswordResetController, :edit
    put "/forgot_password/reset/:token_string", PasswordResetController, :update

    get "/", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    delete "/logout", SessionController, :delete # Exadmin logout needs this
  end

  scope "/admin", Pairmotron do
    pipe_through [:browser, :authenticate, :admin]
    get "/", AdminController, :index
    resources "/users", AdminUserController
    resources "/groups", AdminGroupController
    resources "/projects", AdminProjectController
    resources "/user_groups", AdminUserGroupController
    resources "/group_membership_requests", AdminGroupMembershipRequestController
    put "/invitation_accept/:user_id/:group_membership_request_id", AdminInvitationAcceptController, :update
  end

  scope "/", Pairmotron do
    pipe_through [:browser, :authenticate]

    get "/profile", ProfileController, :show
    get "/profile/edit", ProfileController, :edit
    put "/profile/update/:id", ProfileController, :update
    resources "/projects", ProjectController

    get "/pairs", PairController, :index
    get "/pairs/:date", PairController, :from_date
    get "/pairs/:year/:week", PairController, :show

    get "/groups/:id/pairs", GroupPairController, :show
    get "/groups/:id/pairs/:year/:week", GroupPairController, :show
    delete "/groups/:id/pairs/:year/:week", GroupPairController, :delete
    resources "/groups/:group_id/invitations", GroupInvitationController, only: [:index, :new, :create, :update, :delete]
    resources "/invitations", UsersGroupMembershipRequestController, only: [:index, :create, :update, :delete]
    resources "/groups", GroupController
    delete "/groups/:group_id/users/:user_id", UserGroupController, :delete
    get "/groups/:group_id/users/:user_id", UserGroupController, :edit
    put "/groups/:group_id/users/:user_id", UserGroupController, :update

    get "/pair_retros/new/:pair_id", PairRetroController, :new
    resources "/pair_retros", PairRetroController, except: [:new]
  end

end

web/views/layout_view.ex
defmodule Pairmotron.LayoutView do
  @moduledoc false
  use Pairmotron.Web, :view

  @spec logged_in?(%Plug.Conn{}) :: boolean()
  def logged_in?(conn) do
    !!conn.assigns[:current_user]
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Pairmotron!</title>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav role="navigation" class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link "Pairmotron", to: pair_path(@conn, :index), class: "logo navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <%= if logged_in?(@conn) do %>
              <li><%= link "Pairs", to: pair_path(@conn, :index) %></li>
              <li><%= link "Groups", to: group_path(@conn, :index) %></li>
              <li><%= link "Projects", to: project_path(@conn, :index) %></li>
              <li class="dropdown" role="presentation">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @conn.assigns.current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link "Profile", to: profile_path(@conn, :show) %></li>
                  <li><%= link "Retrospectives", to: pair_retro_path(@conn, :index) %></li>
                  <li><%= link "Invitations", to: users_group_membership_request_path(@conn, :index)%></li>
                </ul>
              </li>
            <%= end %>
            <%= if logged_in?(@conn) do %>
              <li><%= link "Logout", to: session_path(@conn, :delete) %></li>
            <%= else %>
              <%= link "Login", class: "btn btn-success navbar-btn", role: "button", to: session_path(@conn, :new) %>
            <%= end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container paneled">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>