web/router.ex
defmodule Pairmotron.Router do
  use Pairmotron.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :authenticate do
    plug Pairmotron.Plug.RequireAuthentication
  end

  pipeline :admin do
    plug Pairmotron.Plug.RequireAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  scope "/", Pairmotron do
    pipe_through :browser

    resources "/registration", RegistrationController, only: [:new, :create]
    get "/forgot_password", PasswordResetController, :new
    post "/forgot_password", PasswordResetController, :create
    get "/forgot_password/reset/:token_string", PasswordResetController, :edit
    put "/forgot_password/reset/:token_string", PasswordResetController, :update

    get "/", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    delete "/logout", SessionController, :delete # Exadmin logout needs this
  end

  scope "/admin", Pairmotron do
    pipe_through [:browser, :authenticate, :admin]
    get "/", AdminController, :index
    resources "/users", AdminUserController
    resources "/groups", AdminGroupController
    resources "/projects", AdminProjectController
    resources "/user_groups", AdminUserGroupController
    resources "/group_membership_requests", AdminGroupMembershipRequestController
    put "/invitation_accept/:user_id/:group_membership_request_id", AdminInvitationAcceptController, :update
  end

  scope "/", Pairmotron do
    pipe_through [:browser, :authenticate]

    get "/profile", ProfileController, :show
    get "/profile/edit", ProfileController, :edit
    put "/profile/update/:id", ProfileController, :update
    resources "/projects", ProjectController

    get "/pairs", PairController, :index
    get "/pairs/:date", PairController, :from_date
    get "/pairs/:year/:week", PairController, :show

    get "/groups/:id/pairs", GroupPairController, :show
    get "/groups/:id/pairs/:year/:week", GroupPairController, :show
    delete "/groups/:id/pairs/:year/:week", GroupPairController, :delete
    resources "/groups/:group_id/invitations", GroupInvitationController, only: [:index, :new, :create, :update, :delete]
    resources "/invitations", UsersGroupMembershipRequestController, only: [:index, :create, :update, :delete]
    resources "/groups", GroupController
    delete "/groups/:group_id/users/:user_id", UserGroupController, :delete
    get "/groups/:group_id/users/:user_id", UserGroupController, :edit
    put "/groups/:group_id/users/:user_id", UserGroupController, :update

    get "/pair_retros/new/:pair_id", PairRetroController, :new
    resources "/pair_retros", PairRetroController, except: [:new]
  end

end

web/views/admin_group_view.ex
defmodule Pairmotron.AdminGroupView do
  use Pairmotron.Web, :view
end

web/templates/admin_group/edit.html.eex
<h2>Edit Group (Admin)</h2>

<%= render "form.html", changeset: @changeset,
                        action: admin_group_path(@conn, :update, @group),
                        users: @users %>

<%= link "Back", to: admin_group_path(@conn, :index) %>

web/templates/admin_group/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :owner_id, "Owner", class: "control-label" %>
    <%= select f, :owner_id, data_as_select_with_ids(@users), prompt: "(none)", class: "form-control" %>
    <%= error_tag f, :owner_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/admin_group/index.html.eex
<h2>Listing Groups (Admin)</h2>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Owner</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for group <- @groups do %>
    <tr>
      <td><%= group.id %></td>
      <td><%= group.name %></td>
      <td>
        <%= if is_nil(group.owner) do %>
          (none)
        <%= else %>
          <%= link group.owner.name, to: admin_user_path(@conn, :show, group.owner) %></td>
        <%= end %>
      </td>
      <td class="text-right">
        <%= link "Show", to: admin_group_path(@conn, :show, group), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: admin_group_path(@conn, :edit, group), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: admin_group_path(@conn, :delete, group), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New group", to: admin_group_path(@conn, :new) %>

web/templates/admin_group/new.html.eex
<h2>New Group (Admin)</h2>

<%= render "form.html", changeset: @changeset,
                        action: admin_group_path(@conn, :create),
                        users: @users %>

<%= link "Back", to: admin_group_path(@conn, :index) %>

web/templates/admin_group/show.html.eex
<h2>Show Group (Admin)</h2>

<ul>

  <li>
    <strong>id:</strong>
    <%= @group.id %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @group.name %>
  </li>

  <li>
    <strong>Owner:</strong>
    <%= if is_nil(@group.owner) do %>
      (none)
    <%= else %>
      <%= link @group.owner.name, to: admin_user_path(@conn, :show, @group.owner) %></td>
    <%= end %>
  </li>

</ul>

<%= link "Edit", to: admin_group_path(@conn, :edit, @group) %>
<%= link "Back", to: admin_group_path(@conn, :index) %>