web/router.ex
defmodule Pairmotron.Router do
  use Pairmotron.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :authenticate do
    plug Pairmotron.Plug.RequireAuthentication
  end

  pipeline :admin do
    plug Pairmotron.Plug.RequireAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  scope "/", Pairmotron do
    pipe_through :browser

    resources "/registration", RegistrationController, only: [:new, :create]
    get "/forgot_password", PasswordResetController, :new
    post "/forgot_password", PasswordResetController, :create
    get "/forgot_password/reset/:token_string", PasswordResetController, :edit
    put "/forgot_password/reset/:token_string", PasswordResetController, :update

    get "/", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    delete "/logout", SessionController, :delete # Exadmin logout needs this
  end

  scope "/admin", Pairmotron do
    pipe_through [:browser, :authenticate, :admin]
    get "/", AdminController, :index
    resources "/users", AdminUserController
    resources "/groups", AdminGroupController
    resources "/projects", AdminProjectController
    resources "/user_groups", AdminUserGroupController
    resources "/group_membership_requests", AdminGroupMembershipRequestController
    put "/invitation_accept/:user_id/:group_membership_request_id", AdminInvitationAcceptController, :update
  end

  scope "/", Pairmotron do
    pipe_through [:browser, :authenticate]

    get "/profile", ProfileController, :show
    get "/profile/edit", ProfileController, :edit
    put "/profile/update/:id", ProfileController, :update
    resources "/projects", ProjectController

    get "/pairs", PairController, :index
    get "/pairs/:date", PairController, :from_date
    get "/pairs/:year/:week", PairController, :show

    get "/groups/:id/pairs", GroupPairController, :show
    get "/groups/:id/pairs/:year/:week", GroupPairController, :show
    delete "/groups/:id/pairs/:year/:week", GroupPairController, :delete
    resources "/groups/:group_id/invitations", GroupInvitationController, only: [:index, :new, :create, :update, :delete]
    resources "/invitations", UsersGroupMembershipRequestController, only: [:index, :create, :update, :delete]
    resources "/groups", GroupController
    delete "/groups/:group_id/users/:user_id", UserGroupController, :delete
    get "/groups/:group_id/users/:user_id", UserGroupController, :edit
    put "/groups/:group_id/users/:user_id", UserGroupController, :update

    get "/pair_retros/new/:pair_id", PairRetroController, :new
    resources "/pair_retros", PairRetroController, except: [:new]
  end

end

web/controllers/password_reset_controller.ex
defmodule Pairmotron.PasswordResetController do
  @moduledoc """
  Handles users requesting a password reset email. Renders a form for entering
  which email to send a password reset token to, as well as generating that
  token and sending it.
  """
  use Pairmotron.Web, :controller

  alias Pairmotron.{PasswordResetToken, PasswordResetTokenService, User}

  @spec new(%Plug.Conn{}, map()) :: %Plug.Conn{}
  def new(conn, _params) do
    changeset = PasswordResetToken.changeset(%PasswordResetToken{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  @spec create(%Plug.Conn{}, map()) :: %Plug.Conn{}
  def create(conn, %{"password_reset_token" => %{"email" => email}}) do
    with {:ok, token} <- PasswordResetTokenService.generate_token(email),
      do: send_password_reset_email(token)
    render(conn, "email_sent.html")
  end

  @spec send_password_reset_email(Types.password_reset_token) :: any
  defp send_password_reset_email(token) do
    token
    |> Pairmotron.Email.password_reset_email
    |> Pairmotron.Mailer.deliver_now
  end

  @spec edit(%Plug.Conn{}, map()) :: %Plug.Conn{}
  def edit(conn, %{"token_string" => token_string}) do
    case PasswordResetTokenService.verify_token(token_string) do
      {:ok, _valid_token} ->
        changeset = User.password_reset_changeset(%User{})
        render(conn, "reset.html", changeset: changeset, token_string: token_string)
      {:error, :token_not_found} ->
        conn
        |> put_flash(:error, "Sorry, that is not a valid password reset token")
        |> redirect(to: session_path(conn, :new))
      {:error, :token_expired} ->
        conn
        |> put_flash(:error, "Sorry, that password reset token has expired.")
        |> redirect(to: session_path(conn, :new))
    end
  end

  @spec update(%Plug.Conn{}, map()) :: %Plug.Conn{}
  def update(conn, %{"token_string" => token_string, "user" => user_params}) do
    case PasswordResetTokenService.verify_token(token_string) do
      {:ok, valid_token} ->
        changeset = User.password_reset_changeset(valid_token.user, user_params)
        transaction = update_transaction(changeset, valid_token)
        case Repo.transaction(transaction) do
          {:ok, _} ->
            conn
            |> Guardian.Plug.sign_in(valid_token.user)
            |> put_flash(:info, "Password successfully reset")
            |> redirect(to: pair_path(conn, :index))
          {:error, :user_update, changeset, _} ->
            render(conn, "reset.html", changeset: changeset, token_string: token_string)
          _ ->
            render(conn, "reset.html", changeset: changeset, token_string: token_string)
        end
      {:error, _} ->
        conn
        |> put_flash(:error, "Sorry, that is not a valid password reset token")
        |> redirect(to: session_path(conn, :new))
    end
  end

  @spec update_transaction(Ecto.Changeset.t, Types.password_reset_token) :: Ecto.Multi.t
  defp update_transaction(user_changeset, token) do
    Ecto.Multi.new
    |> Ecto.Multi.update(:user_update, user_changeset)
    |> Ecto.Multi.delete(:token_delete, token)
  end
end

web/templates/password_reset/email_sent.html.eex
<h3>Forgot Password</h3>
<p class="lead">
  An email with password reset instructions has been sent.
</p>

web/templates/password_reset/new.html.eex
<h3>Forgot Password</h3>

<p class="lead">Enter the email associated with your account and instructions for resetting your password will be sent.</p>

<%= form_for @changeset, password_reset_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>There was a problem sending a password reset email.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Send Password Reset Email", class: "btn btn-primary pull-right" %>
  </div>
<% end %>

web/templates/password_reset/reset.html.eex
<p class="lead">Enter new password</p>

<%= form_for @changeset, password_reset_path(@conn, :update, @token_string), [method: :put], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>There was a problem resetting your password.</p>
    </div>
  <% end %>

  <%= hidden_input f, :token, value: value_from_changeset(@changeset, :token) %>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary pull-right" %>
  </div>
<% end %>